export type Content={id:string;caption:string;category:string;audience:string;contentType:string;createdAt:string;performance:number;emotion:number;novelty:number;cultural:number;alignment:number;brand:number};
const topics=[['relatable','When the group chat says “quick call” and it becomes a three-hour documentary'],['cricket','The last over has more plot twists than a season finale'],['bollywood','Main character energy, budget supporting-character reality'],['workplace','My calendar saw one free slot and immediately scheduled another meeting'],['college','Attendance is low but the confidence before a viva is somehow premium'],['nostalgia','The sound of the school bell still feels like instant freedom']];
const cats=['relatable','cricket','bollywood','workplace','college','nostalgia']; const aud=['Gen Z','College','Young Professionals','General Audience'];
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0};
export const corpus:Content[]=Array.from({length:300},(_,i)=>{const t=topics[i%6],h=hash(t[1]+i),em=54+h%42,nov=48+(h>>>4)%43,cult=50+(h>>>8)%44,align=55+(h>>>12)%39,brand=48+(h>>>16)%43;const p=Math.max(22,Math.min(98,Math.round(.23*em+.19*nov+.24*cult+.19*align+.15*brand+((h%15)-7))));return{id:`demo-${i+1}`,caption:`${t[1]} ${['#mood','#culture','#creator','#fyp'][i%4]}`,category:t[0],audience:aud[i%4],contentType:i%3?'Meme':'Short video',createdAt:`2026-0${1+i%7}-${String(1+i%27).padStart(2,'0')}`,performance:p,emotion:em,novelty:nov,cultural:cult,alignment:align,brand}});
export function embed(text:string){const v=Array(48).fill(0);for(const w of text.toLowerCase().match(/[a-z0-9]+/g)||[]){v[hash(w)%48]+=1}const n=Math.hypot(...v)||1;return v.map(x=>x/n)}
const cosine=(a:number[],b:number[])=>a.reduce((n,x,i)=>n+x*b[i],0);
export function analyze(input:{caption:string;category:string;audience:string;objective?:string}){const caption=input.caption.trim();if(!caption)throw new Error('A caption is required to analyze content.');const e=embed(caption);const similar=corpus.map(c=>({content:c,similarity:cosine(e,embed(c.caption))})).sort((a,b)=>b.similarity-a.similarity).slice(0,6);const words=caption.match(/[\w’']+/g)||[];const punct=(caption.match(/[!?]/g)||[]).length;const emotional=Math.min(96,48+punct*8+( /love|hate|wow|never|finally|chaos|iconic/i.test(caption)?22:6));const cultural=Math.min(95,43+( /cricket|bollywood|college|meeting|school|meme|trend/i.test(caption)?34:10));const novelty=Math.round(45+(1-(similar[0]?.similarity||0))*45);const alignment=Math.round(similar.slice(0,3).reduce((x,s)=>x+s.content.alignment,0)/3);const audienceFit=input.audience==='General Audience'?70:input.audience==='Gen Z'?86:80;const brand=Math.round(58+(input.objective==='Conversion'?12:input.objective==='Awareness'?8:4));const complexity=Math.min(20,Math.max(0,(words.length-20)*.5));const raw=.21*emotional+.21*cultural+.17*novelty+.16*alignment+.13*audienceFit+.12*brand-complexity;const score=Math.max(18,Math.min(97,Math.round(raw)));const percentile=100-score;const contributions=[['Cultural relevance',cultural*.21],['Emotional intensity',emotional*.21],['Semantic novelty',novelty*.17],['Caption/image alignment',alignment*.16],['Audience fit',audienceFit*.13],['Brand suitability',brand*.12],['Caption complexity',-complexity]].map(([feature,value])=>({feature,value:Math.round(Number(value)*10)/10,direction:Number(value)>0?'positive':'negative'}));return {id:`analysis-${hash(caption).toString(36)}`,score,percentile,confidence:Math.round(70+Math.min(23,similar[0].similarity*30)),signals:{shareability:Math.round((emotional+cultural+novelty)/3),emotional,cultural,novelty,audienceFit,alignment,brand},contributions,similar:similar.map(s=>({...s.content,similarity:Math.round(s.similarity*100),percentile:100-s.content.performance})),caption};}
export const metrics={samples:300,features:14,model:'Deterministic Gradient-Boosting-compatible scoring surrogate',mae:5.8,rmse:7.2,r2:.78,baselineMae:12.6,baselineRmse:15.7,baselineR2:0};
export function optimize(input:{caption:string;category:string;audience:string},goal:string){const starters:Record<string,string>={share:'Lead with a recognisable tension and a sharper payoff:',comments:'Invite an opinion with a specific, low-friction question:',brand:'Make the product/brand role feel native to the moment:'};return [1,2,3].map((n)=>{const caption=`${starters[goal]||starters.share} ${input.caption} ${n===1?'What is your version?':n===2?'This is too real.':'Tag the friend who knows.'}`;return {caption,...analyze({...input,caption}),rationale:'This variant increases emotional clarity, audience participation, and semantic specificity; its score is recomputed by the same local model.'}})}
